--------------------------------------------

DROP TABLE CARD_COLLECTIONS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CARD;

CREATE TABLE CARD_COLLECTIONS(
    CARDSEQ NUMBER(8) PRIMARY KEY,
	CARDTITLE VARCHAR2(100) NOT NULL,
	CARDCONTENT VARCHAR2(500) NOT NULL,
	USERSEQ NUMBER(8) NOT NULL,
	CARDREADCOUNT NUMBER(8) NOT NULL,
	CARDDATE DATE NOT NULL,
    CARDFILENAME VARCHAR2(100) NOT NULL,
    CARDDEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_CARD
START WITH 1
INCREMENT BY 1;


INSERT INTO CARD_COLLECTIONS  VALUES (SEQ_CARD.NEXTVAL, '테스트1', '테스트글1', 1, 0, SYSDATE, '123.jpg', 0);
commit;

---------------------------------------------

DROP TABLE CARD_FAVORITE
CASCADE CONSTRAINTS;

CREATE TABLE CARD_FAVORITE(
    USERSEQ NUMBER(8) NOT NULL,
    CARDSEQ NUMBER(8) NOT NULL
);

ALTER TABLE CARD_FAVORITE
ADD CONSTRAINT FK_FAVO_CARDSEQ FOREIGN KEY(CARDSEQ)
REFERENCES CARD_COLLECTIONS(CARDSEQ);



----------------------------------------------


DROP TABLE CARD_REVIEW
CASCADE CONSTRAINTS;

CREATE TABLE CARD_REVIEW(
    CARDREVSEQ NUMBER(8) PRIMARY KEY,
    CARDSEQ NUMBER(8) NOT NULL,
    NICKNAME VARCHAR2(20) NOT NULL,
    CARDREVCONTENT VARCHAR2(100) NOT NULL,
    CARDREVDATE DATE NOT NULL,
    CARDREVDEL NUMBER(1) NOT NULL,
    CONSTRAINT FK_REVIEW_CARDSEQ FOREIGN KEY(CARDSEQ)
    REFERENCES CARD_COLLECTIONS(CARDSEQ)
);



----------------------------------------------
DROP TABLE CARD_TAG
CASCADE CONSTRAINTS;

CREATE TABLE CARD_TAG(
    CARDSEQ NUMBER(8) NOT NULL,
    TAGCOLOR VARCHAR2(50),
    TAGHOMETYPE VARCHAR2(50),
    TAGSTYLE VARCHAR2(50),
    CONSTRAINT FK_TAG_CARDSEQ FOREIGN KEY(CARDSEQ)
    REFERENCES CARD_COLLECTIONS(CARDSEQ)
);

----------------------------------------------

DROP TABLE CARD_COORDINATES
CASCADE CONSTRAINTS;

CREATE TABLE CARD_COORDINATES(
    CARDSEQ NUMBER(8) NOT NULL,
    PRODUCTSEQ NUMBER(8) NOT NULL,
    LOCATIONX NUMBER(8),
    LOCATIONY NUMBER(8),
    CONSTRAINT FK_COORDI_CARDSEQ FOREIGN KEY(CARDSEQ)
    REFERENCES CARD_COLLECTIONS(CARDSEQ)
);


-----------------------------------------------



